In [68]:
from PIL import Image
import numpy as np

In [69]:
img = Image.open("Unknown.jpeg")

In [70]:
imageArray = np.array(img)
imageArray = imageArray.reshape(len(imageArray),len(imageArray[0])*3)

In [71]:
len(imageArray[0])%12

3

In [72]:
imageArray = np.pad(imageArray, ((0, 12 - (len(imageArray)%12)),
                                 (0, 12 - (len(imageArray[0])%12))), constant_values = (0,0))

In [73]:
len(imageArray)

228

In [95]:
blocks = np.array([[imageArray[i:i+4, j:j+4] for j in range(0,len(imageArray[0]),4)] for i in range(0,len(imageArray),4)])

In [96]:
newBlocks = np.array([imageArray[i:i+4, j:j+4] for i in range(0,len(imageArray),4) for j in range(0,len(imageArray[0]),4)])

In [76]:
a = np.array([[ 62,  62,  62,  63],
         [ 57,  57,  57,  58],
         [ 53,  53,  53,  54],
         [ 55,  55,  55,  56]])

In [77]:
x = np.concatenate((a,a), axis = 1)

In [78]:
x

array([[62, 62, 62, 63, 62, 62, 62, 63],
       [57, 57, 57, 58, 57, 57, 57, 58],
       [53, 53, 53, 54, 53, 53, 53, 54],
       [55, 55, 55, 56, 55, 55, 55, 56]])

In [79]:
y = np.array([[50, 62, 62, 63, 62, 62, 62, 63],
       [57, 57, 57, 58, 57, 57, 57, 58],
       [53, 53, 53, 54, 53, 53, 53, 54],
       [55, 55, 55, 56, 55, 55, 55, 100]])

In [80]:
y

array([[ 50,  62,  62,  63,  62,  62,  62,  63],
       [ 57,  57,  57,  58,  57,  57,  57,  58],
       [ 53,  53,  53,  54,  53,  53,  53,  54],
       [ 55,  55,  55,  56,  55,  55,  55, 100]])

In [81]:
np.concatenate((x,y))

array([[ 62,  62,  62,  63,  62,  62,  62,  63],
       [ 57,  57,  57,  58,  57,  57,  57,  58],
       [ 53,  53,  53,  54,  53,  53,  53,  54],
       [ 55,  55,  55,  56,  55,  55,  55,  56],
       [ 50,  62,  62,  63,  62,  62,  62,  63],
       [ 57,  57,  57,  58,  57,  57,  57,  58],
       [ 53,  53,  53,  54,  53,  53,  53,  54],
       [ 55,  55,  55,  56,  55,  55,  55, 100]])

In [82]:
from functools import reduce
def combineRows(blocks):
    rows = np.array([combineColumns(blocks[i]) for i in range(0,len(blocks))])
    return reduce((lambda a,b : np.concatenate((a,b))), rows)
    
def combineColumns(row):
    return reduce((lambda a,b : np.concatenate((a,b), axis = 1)), row)

In [83]:
combineRows(blocks)

array([[154, 154, 154, ...,   0,   0,   0],
       [154, 154, 154, ...,   0,   0,   0],
       [153, 153, 153, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [84]:
combinedBlocks = combineRows(blocks)
combinedBlocks

array([[154, 154, 154, ...,   0,   0,   0],
       [154, 154, 154, ...,   0,   0,   0],
       [153, 153, 153, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [85]:
def makeRGBArray(arr):
    return np.array([arr[i].reshape(len(arr[i])//3, 3) for i in range(0, len(arr))])

In [86]:
newImage = Image.fromarray(makeRGBArray(combinedBlocks), 'RGB')

In [87]:
newImage.show()

In [88]:
makeRGBArray(combinedBlocks)

array([[[154, 154, 154],
        [154, 154, 154],
        [154, 154, 154],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[154, 154, 154],
        [154, 154, 154],
        [154, 154, 154],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[153, 153, 153],
        [153, 153, 153],
        [153, 153, 153],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [89]:
blocks

array([[[[154, 154, 154, 154],
         [154, 154, 154, 154],
         [153, 153, 153, 153],
         [152, 152, 152, 152]],

        [[154, 154, 154, 154],
         [154, 154, 154, 154],
         [153, 153, 153, 153],
         [152, 152, 152, 152]],

        [[154, 154, 154, 154],
         [154, 153, 153, 153],
         [153, 152, 152, 152],
         [152, 151, 151, 151]],

        ...,

        [[140, 140, 140,   0],
         [145, 145, 145,   0],
         [ 97,  97,  97,   0],
         [ 26,  26,  26,   0]],

        [[  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0]],

        [[  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0]]],


       [[[151, 151, 151, 151],
         [150, 150, 150, 150],
         [149, 149, 149, 149],
         [149, 149, 149, 149]],

        [[151, 151, 151, 151],
         [150, 150, 150, 150],
         [149, 149, 149, 149],
         

In [90]:
h,w = len(blocks), len(blocks[0])
flattned = reduce((lambda a, b : np.concatenate((a, b))), blocks)

In [91]:
rearranged = np.array([flattned[i:i+w] for i in range(0, len(flattned), w)])

In [92]:
rearranged

array([[[[154, 154, 154, 154],
         [154, 154, 154, 154],
         [153, 153, 153, 153],
         [152, 152, 152, 152]],

        [[154, 154, 154, 154],
         [154, 154, 154, 154],
         [153, 153, 153, 153],
         [152, 152, 152, 152]],

        [[154, 154, 154, 154],
         [154, 153, 153, 153],
         [153, 152, 152, 152],
         [152, 151, 151, 151]],

        ...,

        [[140, 140, 140,   0],
         [145, 145, 145,   0],
         [ 97,  97,  97,   0],
         [ 26,  26,  26,   0]],

        [[  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0]],

        [[  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0],
         [  0,   0,   0,   0]]],


       [[[151, 151, 151, 151],
         [150, 150, 150, 150],
         [149, 149, 149, 149],
         [149, 149, 149, 149]],

        [[151, 151, 151, 151],
         [150, 150, 150, 150],
         [149, 149, 149, 149],
         

In [93]:
flattned

array([[[154, 154, 154, 154],
        [154, 154, 154, 154],
        [153, 153, 153, 153],
        [152, 152, 152, 152]],

       [[154, 154, 154, 154],
        [154, 154, 154, 154],
        [153, 153, 153, 153],
        [152, 152, 152, 152]],

       [[154, 154, 154, 154],
        [154, 153, 153, 153],
        [153, 152, 152, 152],
        [152, 151, 151, 151]],

       ...,

       [[ 97,  97,  97,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]], dtype=uint8)

In [94]:
newBlocks

array([[[154, 154, 154, 154],
        [154, 154, 154, 154],
        [153, 153, 153, 153],
        [152, 152, 152, 152]],

       [[154, 154, 154, 154],
        [154, 154, 154, 154],
        [153, 153, 153, 153],
        [152, 152, 152, 152]],

       [[154, 154, 154, 154],
        [154, 153, 153, 153],
        [153, 152, 152, 152],
        [152, 151, 151, 151]],

       ...,

       [[ 97,  97,  97,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]],

       [[  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0],
        [  0,   0,   0,   0]]], dtype=uint8)